/* eslint-disable react/jsx-no-constructed-context-values */
import Head from 'next/head';
import { ReactNode, createContext } from 'react';
import Header from './Header';
import { useWhoAmIQuery } from '../types/graphql';

export const UserContext = createContext({
  isLoggedIn: false,
  refetchLogin: () => {},
  role: 'user',
});

function Layout({ children }: { children: ReactNode }) {
  const {
    data, loading, error, refetch,
  } = useWhoAmIQuery();

  if (loading) {
    return <p>Loading</p>;
  }
  if (error) {
    return <p>Error</p>;
  }

  if (data?.whoAmI.role) {
    // console.log('whoami', data);

    return (

      <UserContext.Provider
        value={{
          isLoggedIn: data.whoAmI.isLoggedIn,
          refetchLogin: refetch,
          role: data.whoAmI.role,
        }}
      >
        <Head>
          <title>The Good Corner</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className="main-content">{children}</main>
      </UserContext.Provider>
    );
  }
}

export default Layout;
