import Head from 'next/head';
import { ReactNode } from 'react';
import styles from '@/styles/Layout.module.css';
import Header from './Header';

function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>The Good Corner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.mainContent}>{children}</main>
    </>

  );
}

export default Layout;
