/* eslint-disable react/jsx-no-constructed-context-values */
import Head from 'next/head';
import { ReactNode, createContext } from 'react';
import { useQuery } from '@apollo/client';
import styles from '../styles/Layout.module.css';
import Header from './Header';
import { GET_AUTH_INFO } from '../graphql/queries/queries';

export const UserContext = createContext({
  isLoggedIn: false,
  refetchLogin: () => {},
  role: 'user',
});

function Layout({ children }: { children: ReactNode }) {
  const {
    data, loading, error, refetch,
  } = useQuery(GET_AUTH_INFO);

  if (loading) {
    return <p>Loading</p>;
  }
  if (error) {
    return <p>Error</p>;
  }

  if (data) {
    console.log('whoami', data);

    return (

      <UserContext.Provider
        value={{
          isLoggedIn: data.whoAmI.isLoggedIn,
          refetchLogin: refetch,
          role: data.whoAmI.role,
        }}
      >
        <Head>
          <title>The Good Corner</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className={styles.mainContent}>{children}</main>
      </UserContext.Provider>
    );
  }
}

export default Layout;
