GET http://localhost:4000/category

###
GET http://localhost:4000/category?name=Ameublement

###
POST http://localhost:4000/category
Content-Type: application/json

{
  "name": "Vehicule"
}

###
DELETE http://localhost:4000/category
Content-Type: application/json

{
  "id": 2
}

###
PUT http://localhost:4000/category
Content-Type: application/json

{
  "id": 1,
  "name": "informatique"
}





